# Generated by Django 3.0.4 on 2020-07-29 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('espera', 'En espera'), ('proceso', 'En proceso'), ('reserva', 'En reserva'), ('aceptado', 'Aceptado'), ('denegado', 'Denegado')], default='espera', max_length=9),
        ),
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 1, 25), verbose_name='Fecha de Fin'),
        ),
    ]
