# Generated by Django 3.0.4 on 2020-07-30 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0002_auto_20200729_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 1, 26), verbose_name='Fecha de Fin'),
        ),
    ]
