# Generated by Django 3.0.4 on 2020-08-03 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0003_auto_20200730_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformation',
            name='adminteachers',
            field=models.ManyToManyField(related_name='teachers', related_query_name='teacher_admin', to='Docencia.TeacherPersonalInformation', verbose_name='Profesores Encargados'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 1, 30), verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(default='Aug 2020-Aug 2021', max_length=17, unique=True, verbose_name='Curso - Edición'),
        ),
    ]
