# Generated by Django 3.0.4 on 2020-08-07 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0004_auto_20200803_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Nombre')),
                ('addr', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
                ('openhor', models.TimeField(verbose_name='Apertura')),
                ('closehor', models.TimeField(verbose_name='Cierre')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 2, 3), verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='sedes',
            field=models.ManyToManyField(related_name='sedes', related_query_name='sedes', to='Docencia.Sede', verbose_name='Sede(s)'),
        ),
    ]
