# Generated by Django 3.0.4 on 2020-08-12 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0005_auto_20200807_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaskapplication',
            name='ispositive',
            field=models.BooleanField(default=False, verbose_name='¿Es Respuesta Positiva?'),
        ),
        migrations.AlterField(
            model_name='askapplication',
            name='askType',
            field=models.CharField(choices=[('t', 'Texto'), ('o', 'Opciones'), ('r', 'Radio Botón'), ('c', 'Check Botón')], default='t', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 2, 8), verbose_name='Fecha de Fin'),
        ),
    ]
