# Generated by Django 3.0.4 on 2020-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0006_auto_20200812_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='askapplication',
            name='textMin',
            field=models.PositiveIntegerField(default=20, verbose_name='Cantidad Mínima de Caracteres en la Respuesta'),
        ),
        migrations.AlterField(
            model_name='askapplication',
            name='textMax',
            field=models.PositiveIntegerField(default=200, verbose_name='Cantidad Máxima de Caracteres Permitidos en la Respuesta'),
        ),
    ]
