# Generated by Django 3.0.4 on 2020-08-12 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Docencia', '0007_auto_20200812_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpersonalinformation',
            name='dateend',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='teacherpersonalinformation',
            name='dateinit',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='curriculum',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Curriculum'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='deadline',
            field=models.DateField(blank=True, verbose_name='Fin Admisión'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Descripión'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='haveApplication',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Formulario de Aplicación?'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='openregistre',
            field=models.DateField(blank=True, verbose_name='Inicio Admisión'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='price',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='requirements',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='yearMax',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='Edad Máxima'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='yearMin',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='Edad Minima'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='cellphone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Móvil'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='degree',
            field=models.CharField(choices=[('Ing.', 'Ingeniero'), ('Lic.', 'Licenciado'), ('Ms.C.', 'Master en Ciencias'), ('Dr.C.', 'Doctor en Ciencias'), ('PhD.C.', 'Postdoctor en Ciencias'), ('Ning.', 'Ninguno')], default='Lic.', max_length=20, verbose_name='Grado Científico'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='gender',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='nacionality',
            field=models.CharField(default='cubana', max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='numberidentification',
            field=models.CharField(max_length=11, unique=True, verbose_name='Carnet de Identidad'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='pasaport',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pasaporte'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('gender', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=1, verbose_name='Género')),
                ('numberidentification', models.CharField(max_length=11, unique=True, verbose_name='Carnet de Identidad')),
                ('street', models.CharField(max_length=100, verbose_name='Calle')),
                ('city', models.CharField(max_length=50, verbose_name='Municipio')),
                ('state', models.CharField(max_length=50, verbose_name='Provincia')),
                ('cellphone', models.CharField(blank=True, max_length=8, null=True, verbose_name='Móvil')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('labor', models.CharField(max_length=1000, verbose_name='Labor')),
                ('dateinit', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('dateend', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='static/curriculum/colaborador', verbose_name='Curriculum')),
            ],
            options={
                'verbose_name': 'Datos Personales - Colaborador',
                'verbose_name_plural': 'Datos Personales - Colaboradores',
                'unique_together': {('name', 'lastname', 'numberidentification', 'email')},
            },
        ),
    ]
