# Generated by Django 3.0.4 on 2020-08-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0008_auto_20200812_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformation',
            name='programa',
            field=models.FileField(blank=True, null=True, upload_to='static/programas', verbose_name='Programa'),
        ),
    ]
