# Generated by Django 3.0.4 on 2020-08-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0010_auto_20200813_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Cuerpo')),
                ('link', models.URLField(blank=True, verbose_name='Enlace')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/image/news')),
                ('date', models.DateTimeField(verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Index - Noticias',
                'verbose_name_plural': 'Index - Noticiass',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Cuerpo')),
                ('link', models.URLField(blank=True, verbose_name='Enlace')),
                ('autor', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='static/image/blog')),
                ('date', models.DateTimeField(verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Index - Blog Post',
                'verbose_name_plural': 'Index - Blog Posts',
            },
        ),
    ]
