# Generated by Django 3.0.4 on 2020-08-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0011_news_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('body', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('date', models.DateTimeField(verbose_name='Fecha Publicación')),
                ('dateEnv', models.DateTimeField(verbose_name='Fecha Evento')),
                ('place', models.CharField(max_length=500, verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Index - Evento',
                'verbose_name_plural': 'Index - Eventos',
                'unique_together': {('name', 'dateEnv')},
            },
        ),
    ]
