# Generated by Django 3.0.4 on 2020-08-14 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0012_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, unique=True, verbose_name='Autor')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/image/comment', verbose_name='Foto Perfil')),
                ('body', models.TextField(max_length=1000, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Index - Comentario',
                'verbose_name_plural': 'Index - Comentario',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('link', models.URLField(verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Index - Link',
                'verbose_name_plural': 'Index - Links',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Index - Noticia', 'verbose_name_plural': 'Index - Noticias'},
        ),
        migrations.RemoveField(
            model_name='sede',
            name='addr',
        ),
        migrations.AddField(
            model_name='events',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/event/file'),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/event/image'),
        ),
        migrations.AddField(
            model_name='sede',
            name='cellphone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Móvil'),
        ),
        migrations.AddField(
            model_name='sede',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='sede',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sede',
            name='isprincipal',
            field=models.BooleanField(default=False, verbose_name='¿Es la Sede Principal?'),
        ),
        migrations.AddField(
            model_name='sede',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='sede',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 2, 10), verbose_name='Fecha de Fin'),
        ),
    ]
