# Generated by Django 3.0.4 on 2020-08-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0013_auto_20200814_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/comment', verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/event/image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/news'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/blog'),
        ),
    ]
