# Generated by Django 3.0.4 on 2020-08-14 10:59

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0014_auto_20200814_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformation',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='static/image/perfil/course/perfildefault.jpg', null=True, upload_to='static/image/perfil/course'),
        ),
    ]
