# Generated by Django 3.0.4 on 2020-08-14 11:20

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0015_auto_20200814_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformation',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='media/image/perfil/course/perfildefault.jpg', null=True, upload_to='media/image/perfil/course'),
        ),
    ]
