# Generated by Django 3.0.4 on 2020-08-14 19:13

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0016_auto_20200814_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformation',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='image/perfil/course'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='programa',
            field=models.FileField(blank=True, null=True, upload_to='media/static/cursos/programas', verbose_name='Programa'),
        ),
    ]
