# Generated by Django 3.0.4 on 2020-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0018_auto_20200815_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('background', models.ImageField(blank=True, null=True, upload_to='static/image/index/bg', verbose_name='Background Image')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/image/index/icon', verbose_name='Icon')),
                ('titleLine1', models.CharField(max_length=12, verbose_name='Título Línea 1')),
                ('titleLine2', models.CharField(blank=True, max_length=12, verbose_name='Título Línea 2')),
                ('titleLine3', models.CharField(blank=True, max_length=12, verbose_name='Título Línea 3')),
                ('subtitle', models.CharField(blank=True, max_length=32, verbose_name='Subtítulo')),
                ('hadBtn1', models.BooleanField(default=False, verbose_name='Añadir Botón 1')),
                ('btn1', models.CharField(blank=True, max_length=5, verbose_name='Botón 1 Texto')),
                ('linkBtn1', models.URLField(blank=True, verbose_name='Botón 1 Enlace')),
                ('hadBtn2', models.BooleanField(default=False, verbose_name='Añadir Botón 2')),
                ('btn2', models.CharField(blank=True, max_length=5, verbose_name='Botón 2 Texto')),
                ('linkBtn2', models.URLField(blank=True, verbose_name='Botón 2 Enlace')),
            ],
            options={
                'verbose_name': 'Index - Header',
                'verbose_name_plural': 'Index - Header',
            },
        ),
    ]
