# Generated by Django 3.0.4 on 2020-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0019_headerindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerindex',
            name='titleLine1',
            field=models.CharField(max_length=20, verbose_name='Título Línea 1'),
        ),
        migrations.AlterField(
            model_name='headerindex',
            name='titleLine2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Título Línea 2'),
        ),
        migrations.AlterField(
            model_name='headerindex',
            name='titleLine3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Título Línea 3'),
        ),
    ]
