# Generated by Django 3.0.4 on 2020-08-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0021_auto_20200815_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerindex',
            name='linkBtn1',
            field=models.CharField(blank=True, max_length=25, verbose_name='Botón 1 Enlace'),
        ),
        migrations.AlterField(
            model_name='headerindex',
            name='linkBtn2',
            field=models.CharField(blank=True, max_length=25, verbose_name='Botón 2 Enlace'),
        ),
    ]
