# Generated by Django 3.0.4 on 2020-08-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0022_auto_20200815_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerindex',
            name='isVisible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
