# Generated by Django 3.0.4 on 2020-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0023_headerindex_isvisible'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSuscribete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sección Suscribete')),
                ('background', models.ImageField(blank=True, null=True, upload_to='static/image/index/bg', verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Index - Sección Suscríbete',
                'verbose_name_plural': 'Index - Sección Suscríbete',
            },
        ),
    ]
