# Generated by Django 3.0.4 on 2020-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0024_sectionsuscribete'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsuscribete',
            name='cursos',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Cursos'),
        ),
        migrations.AddField(
            model_name='sectionsuscribete',
            name='graduados',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Graduados [mil]'),
        ),
        migrations.AddField(
            model_name='sectionsuscribete',
            name='students',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de Estudiantes [mil]'),
        ),
    ]
