# Generated by Django 3.0.4 on 2020-08-16 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0025_auto_20200815_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('background', models.ImageField(blank=True, null=True, upload_to='static/image/index/bg', verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Index - Sección Comentario',
                'verbose_name_plural': 'Index - Sección Comentarios',
            },
        ),
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 2, 12), verbose_name='Fecha de Fin'),
        ),
    ]
