# Generated by Django 3.0.4 on 2020-08-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0027_links_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('dateEnv', models.DateTimeField(verbose_name='Fecha Evento')),
            ],
            options={
                'verbose_name': 'Index - Evento Fecha',
                'verbose_name_plural': 'Index - Eventos Fechas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together={('name', 'date')},
        ),
        migrations.RemoveField(
            model_name='events',
            name='dateEnv',
        ),
        migrations.AddField(
            model_name='events',
            name='dateEnvs',
            field=models.ManyToManyField(to='Docencia.EventsDate', verbose_name='Fecha(s)'),
        ),
    ]
