# Generated by Django 3.0.4 on 2020-08-16 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0028_auto_20200816_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsdate',
            name='dateFin',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 16, 16, 14, 116878), verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='eventsdate',
            name='dateEnv',
            field=models.DateTimeField(verbose_name='Fecha Inicio'),
        ),
    ]
