# Generated by Django 3.0.4 on 2020-08-16 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0030_auto_20200816_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsdate',
            name='dateFin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Fin'),
        ),
    ]
