# Generated by Django 3.0.4 on 2020-08-17 15:18

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Docencia', '0031_auto_20200816_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Index - Eventos'},
        ),
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 2, 13), verbose_name='Fecha de Fin'),
        ),
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
