# Generated by Django 3.0.4 on 2020-08-17 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0032_auto_20200817_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('dateIni', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('dateFin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Fin')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Cursos - Horarios',
            },
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='schedules',
            field=models.ManyToManyField(to='Docencia.CourseSchedule'),
        ),
    ]
