# Generated by Django 3.0.4 on 2020-08-17 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0033_auto_20200817_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='dateFin',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='dateIni',
            field=models.TimeField(verbose_name='Fecha Inicio'),
        ),
    ]
