# Generated by Django 3.0.4 on 2020-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0034_auto_20200817_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformation',
            name='schedules',
            field=models.ManyToManyField(to='Docencia.CourseSchedule', verbose_name='Horario(s)'),
        ),
    ]
