# Generated by Django 3.0.4 on 2020-08-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0036_courseschedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='weekday',
            field=models.CharField(choices=[('Lun.', 'Lunes'), ('Mar.', 'Martes'), ('Mié.', 'Miércoles'), ('Jue.', 'Jueves'), ('Vie.', 'Viernes'), ('Sáb.', 'Sábado'), ('Lun.-Vie.', 'Lunes a Viernes'), ('Lun.-Sáb.', 'Lunes a Sábado'), ('Lun.,Mié.,Vie.', 'Lunes, Miércoles, Viernes'), ('Mar.,Jue.', 'Martes, Jueves')], default='Lun.', max_length=14),
        ),
    ]
