# Generated by Django 3.0.4 on 2020-08-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0039_events_google_maps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Aplicación - Aplicación Estudiante', 'verbose_name_plural': 'Aplicación - Aplicaciones Estudiante'},
        ),
    ]
