# Generated by Django 3.0.4 on 2020-08-18 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0040_auto_20200817_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 2, 14), verbose_name='Fecha de Fin'),
        ),
    ]
