# Generated by Django 3.0.4 on 2020-08-20 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0041_auto_20200818_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 2, 16), verbose_name='Fecha de Fin'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsdate',
            unique_together={('dateEnv', 'dateFin')},
        ),
        migrations.RemoveField(
            model_name='eventsdate',
            name='name',
        ),
    ]
