# Generated by Django 3.0.4 on 2020-08-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0042_auto_20200820_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformation',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='Docencia.CourseSchedule', verbose_name='Horario(s)'),
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('weekday', 'dateIni', 'dateFin')},
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='name',
        ),
    ]
