# Generated by Django 3.1 on 2020-08-24 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0043_auto_20200820_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='dateend',
            field=models.DateField(default=datetime.date(2021, 2, 20), verbose_name='Fecha de Fin'),
        ),
    ]
