# Generated by Django 3.1 on 2021-01-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('name', models.CharField(max_length=50, verbose_name='Edición')),
                ('datepub', models.DateField(auto_now=True, verbose_name='Fecha Publicación')),
                ('dateupdate', models.DateField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
                'unique_together': {('name', 'datepub')},
            },
        ),
    ]
