# Generated by Django 3.1 on 2021-01-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SapereAude', '0002_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='SectionI',
        ),
        migrations.AlterModelOptions(
            name='sectioni',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
    ]
