# Generated by Django 3.1 on 2021-01-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SapereAude', '0003_auto_20210103_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SapereAude.edition', verbose_name='Edición')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'unique_together': {('edition', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='SectionI',
        ),
    ]
