# Generated by Django 3.1 on 2021-01-03 15:25

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SapereAude', '0005_auto_20210103_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('grade', models.CharField(choices=[('Ing.', 'Ingeniero'), ('Arq.', 'Arquitecto'), ('Lic.', 'Licenciado'), ('Ms.C.', 'Master en Ciencias'), ('Dr.C.', 'Doctor en Ciencias'), ('PhD.C.', 'Postdoctor en Ciencias'), ('', 'Ninguno')], default='', max_length=20, verbose_name='Grado Científico')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('filial', models.CharField(max_length=250, verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'unique_together': {('name', 'lastname')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Subtítulo')),
                ('abstract', models.TextField(verbose_name='Resumen')),
                ('image', models.ImageField(upload_to='static/recurso/%Y/%m/%d/%H/%M/', verbose_name='Imagen')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(default='<p>Sin texto</p>', verbose_name='Cuerpo')),
                ('datepub', models.DateField(auto_now=True, verbose_name='Publicación')),
                ('dateupdate', models.DateField(auto_now=True, verbose_name='Publicación')),
                ('authors', models.ManyToManyField(to='SapereAude.Author', verbose_name='Autor(es)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SapereAude.section', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'unique_together': {('section', 'title')},
            },
        ),
    ]
